name: Build Windows

on:
  workflow_call:
    inputs:
      releaseVersion:
        required: true
        type: string
      artifactArchive:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
        
      - name: Build
        run: msbuild 'cpp/vs2022/vs2022.sln' /p:configuration=Release /p:platform=x64
        
      - name: Archive
        run: |
          New-Item -Path build\DENetwork\DENetworkSDK\Include -ItemType Directory
          New-Item -Path build\DENetwork\DENetworkSDK\Library\x64 -ItemType Directory
          
          Copy-Item -Filter *.h -Path cpp\library\src -Recurse -Destination build\DENetwork\DENetworkSDK\Include
          Move-Item build\DENetwork\DENetworkSDK\Include\src build\DENetwork\DENetworkSDK\Include\denetwork
          
          Copy-Item cpp\vs2022\x64\Release\DENetwork.lib build\DENetwork\DENetworkSDK\Library\x64
          Copy-Item cpp\vs2022\x64\Release\DENetwork.pdb build\DENetwork\DENetworkSDK\Library\x64
          
          Copy-Item LICENSE build\DENetwork\DENetworkSDK
          Copy-Item README.md build\DENetwork\DENetworkSDK
          
          Compress-Archive -Path build\DENetwork\* -DestinationPath DENetworkSDK-${{ inputs.releaseVersion }}.zip

      - name: Store Archives
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactArchive }}
          path: DENetworkSDK-${{ inputs.releaseVersion }}.zip
          if-no-files-found: error
