name: Build Windows

on:
  workflow_call:
    inputs:
      releaseVersion:
        required: true
        type: string
      artifactArchive:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons mingw-w64
      
      - name: Init custom.py
        run: |
          cp ${{ github.workspace }}/.github/workflows/custom_windows.py custom.py
      
      - name: Build
        run: scons -j 14 version=${{ inputs.releaseVersion }} build archive
          
      - name: Store Archives
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactArchive }}
          path: |
            cpp/build/denetworkcpp-windows-x64-${{ inputs.releaseVersion }}.zip
          if-no-files-found: error
