name: Build Linux

on:
  workflow_call:
    inputs:
      releaseVersion:
        required: true
        type: string
      artifactArchive:
        required: true
        type: string

jobs:
  build_linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons
      
      - name: Init custom.py
        run: |
          cp ${{ github.workspace }}/.github/workflows/custom_linux.py custom.py
      
      - name: Build
        run: scons -j 14 version=${{ inputs.releaseVersion }} build archive
        
      - name: Move Artifacts
        run: |
          mkdir artifacts
          mv cpp/library/build/denetworkcpp-unix-x64-${{ inputs.releaseVersion }}.zip artifacts
          mv java/library/build/denetworkjava-${{ inputs.releaseVersion }}.zip artifacts
        
      - name: Store Archives
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactArchive }}
          path: |
            artifacts/denetworkcpp-unix-x64-${{ inputs.releaseVersion }}.zip
            artifacts/denetworkjava-${{ inputs.releaseVersion }}.zip
          if-no-files-found: error
