name: Nightly

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build_linux:
    uses: ./.github/workflows/build_linux.yml
    with:
      releaseVersion: nightly
      artifactArchive: archives-linux
  
  build_windows:
    uses: ./.github/workflows/build_windows.yml
    with:
      releaseVersion: nightly
      artifactArchive: archives-windows
  
  build_android_armv8:
    uses: ./.github/workflows/build_android.yml
    with:
      releaseVersion: nightly
      artifactArchive: archives-android-armv8
      androidArch: armv8
      androidApiLevel: 26
  
  build_android_armv7:
    uses: ./.github/workflows/build_android.yml
    with:
      releaseVersion: nightly
      artifactArchive: archives-android-armv7
      androidArch: armv7
      androidApiLevel: 26
  
  upload:
    needs: [build_linux,
      build_windows,
      build_android_armv8,
      build_android_armv7]
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Linux Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-linux
      
      - name: Get Windows Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-windows
      
      - name: Get Android ArmV8 Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-android-armv8
      
      - name: Get Android ArmV7 Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-android-armv7
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Update git tag
        run: |
          git tag -f nightly
          git push -f origin nightly
      
      - name: Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          draft: false
          prerelease: true
          commit: 'main'
          tag: 'nightly'
          name: 'Drag[en]gine Networking Release - Nightly Build'
          body: |
            Continuous Nightly Build of the Drag[en]gine Networking Libraries.
            Created: ${{ steps.date.outputs.date }}
            
            Builds are potentially unstable. Use at own risk.
          artifacts: |
            artifacts/denetworkcpp-unix-x64-nightly.tar.bz2
            artifacts/denetworkcpp-android-armv8-nightly.tar.bz2
            artifacts/denetworkcpp-android-armv7-nightly.tar.bz2
            artifacts/denetworkjava-nightly.zip
            artifacts/denetworkpython-nightly.zip
            artifacts/DENetworkSDK-nightly.zip
            artifacts/examples.zip
