name: Nightly

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build_linux:
    uses: ./.github/workflows/build_linux.yml
    with:
      releaseVersion: nightly
      artifactArchive: archives-linux
  
  upload:
    needs: [build_linux]
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Linux Archives
        uses: actions/download-artifact@v3
        with:
          name: archives-linux
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          draft: false
          prerelease: true
          commit: 'main'
          tag: 'nightly'
          name: 'Drag[en]gine Networking Release - Nightly Build'
          body: |
            Continuous Nightly Build of the Drag[en]gine Networking Libraries.
            Created: ${{ steps.date.outputs.date }}
            
            Builds are potentially unstable. Use at own risk.
          artifacts: >
            denetworkcpp-unix-x64-nightly.zip
            DENetwork-nightly.jar
